import type { Metadata } from "next";
import localFont from "next/font/local";
import { dark } from "@clerk/themes";
import { ClerkProvider, ClerkLoaded, ClerkLoading } from "@clerk/nextjs";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-appRouter";
import Navbar from "./components/Navbar";
import Loader from "./components/Loader";
import { ThemeProvider } from "./components/ThemeProvider";
import "./globals.css";

const geistSans = localFont({
	src: "./fonts/GeistVF.woff",
	variable: "--font-geist-sans",
	weight: "100 900",
});
const geistMono = localFont({
	src: "./fonts/GeistMonoVF.woff",
	variable: "--font-geist-mono",
	weight: "100 900",
});

export const metadata: Metadata = {
	title: "Next Project 2024",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<ClerkProvider appearance={{ baseTheme: dark }}>
			<html lang='en'>
				<body
					className={`${geistSans.variable} ${geistMono.variable} antialiased`}
				>
					<AppRouterCacheProvider>
						<ThemeProvider
							attribute='class'
							defaultTheme='system'
							enableSystem
							disableTransitionOnChange
						>
							<ClerkLoading>
								<div className='flex items-center justify-center h-screen text-2xl'>
									<Loader />
								</div>
							</ClerkLoading>
							<ClerkLoaded>
								<div className='mx-auto'>
									<Navbar />
									<div className='flex flex-col h-screen py-4'>{children}</div>
								</div>
							</ClerkLoaded>
						</ThemeProvider>
					</AppRouterCacheProvider>
				</body>
			</html>
		</ClerkProvider>
	);
}
